version: "3.7"

services:
  mysql_db:
    image: "mysql:8.0"
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: java_to_dev_app_db
      MYSQL_USER: java_to_dev
      MYSQL_PASSWORD: nE5kMc7JCGNqwDQM
      MYSQL_ROOT_PASSWORD: nE5kMc7JCGNqwDQN
    networks:
      - my-network
  api_service:
    image: darren190196/account-api
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mysql_db
    environment:
      DB_URL: jdbc:mysql://db:3306/java_to_dev_app_db
      DB_USERNAME: java_to_dev
      DB_PASSWORD: nE5kMc7JCGNqwDQM
    networks:
       - my-network
networks:
  my-network:
    driver: bridge


